import { type NextPage } from "next";
import { SessionProvider, signIn } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";

type TParams = {
  session: any;
};

const ErrorPage: NextPage = () => {
  return (
    <>
      <SessionProvider>
        <Head>
          <title>Javelyn - ERRO</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://use.typekit.net/ivi8uyr.css" />
        </Head>
        <main
          className="no-repeat relative flex min-h-screen flex-col items-center justify-center bg-cover backdrop-blur"
          style={{}}
        >
          <div className="absolute inset-0 flex min-h-screen flex-col items-center justify-center backdrop-blur-[20px] ">
            {" "}
            <div className="mb-6">
              <h1 className="bg-gradient-to-r from-[MediumPurple] to-[MediumSlateBlue] bg-clip-text text-5xl font-extrabold text-transparent drop-shadow-xl">
                Javelyn
              </h1>
            </div>
            <span>Houve um erro inesperado.</span>
          </div>
        </main>
      </SessionProvider>{" "}
    </>
  );
};

export default ErrorPage;
